spring.application.name=ms-administracion-archivos
server.port=8080
spring.cloud.aws.region.static=us-east-1
aws.s3.bucket-name=bucketduocs2
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://duocazuredcn1.b2clogin.com/duocazuredcn1.onmicrosoft.com/discovery/v2.0/keys?p=B2C_1_DuocDemoAzure_registro_login



